### ISSUE TITLE
Don't decrease reboot level on multiple runs

### ISSUE THREAD

**Issue by laenion** [openSUSE/zypp-boot-plugin#4]
When running zypper multiple times, then only the reboot level of the last run is stored in _/run/reboot-needed_.

Example:
* `zypper dup` updates a package which would require a `kexec` reboot.
* Before restarting, the user installs an additional package which would "only" require a `soft-reboot`.

Now the reboot level is incorrectly set to `soft-reboot`.

Solution:
Do not just overwrite _/run/reboot-needed_, but only increase the reboot level.

**Comment by schubi2** [comment]
Thanks for the hint. Fixed with version 0.0.8. Ähm, hopefully :-)
